import { Movie } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Interstellar Odyssey',
    year: 2024,
    overview: 'A breathtaking journey through the cosmos as humanity seeks a new home beyond the stars. Set more than a decade after the events of the first film, learn the story of the Nephylis family, the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    runtime: 145,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    poster: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 7.1,
    contentRating: '16+',
    director: 'James Jameson',
    cast: ['Sam Worthing', 'Zoe Weaver', 'Stephen Saldaña', 'Kate Lang', 'John Winslet']
  },
  {
    id: '2',
    title: 'Neon Nights',
    year: 2023,
    overview: 'In a dystopian metropolis, a rogue detective uncovers a conspiracy that threatens the entire city.',
    runtime: 112,
    genres: ['Action', 'Thriller', 'Sci-Fi'],
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 6.8,
    contentRating: '18+',
    director: 'Elena Rostova',
    cast: ['Michael Trent', 'Sarah Connor']
  },
  {
    id: '3',
    title: 'The Silent Peak',
    year: 2022,
    overview: 'An expedition to an uncharted mountain range turns into a desperate fight for survival against the elements.',
    runtime: 128,
    genres: ['Thriller', 'Adventure'],
    poster: 'https://images.unsplash.com/photo-1614729939124-032f0b56c9ce?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 8.2,
    contentRating: '13+',
    director: 'Alan Smithee',
    cast: ['John Doe', 'Jane Doe']
  },
  {
    id: '4',
    title: 'Desert Mirage',
    year: 2025,
    overview: 'A lone traveler navigates a vast, magical desert, searching for an ancient artifact.',
    runtime: 95,
    genres: ['Fantasy', 'Adventure'],
    poster: 'https://images.unsplash.com/photo-1542314831-c5a4d407e201?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 5.5,
    contentRating: 'PG',
    director: 'Jane Smith',
    cast: ['Actor One', 'Actor Two']
  },
  {
    id: '5',
    title: 'Ocean Deep',
    year: 2021,
    overview: 'Explore the uncharted depths of the ocean and discover the mysteries lurking in the abyss.',
    runtime: 104,
    genres: ['Documentary', 'Nature'],
    poster: 'https://images.unsplash.com/photo-1518467166778-b88f373ff255?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    rating: 9.0,
    contentRating: 'G',
    director: 'Jacques Cousteau II',
    cast: ['Narrator']
  },
  {
    id: '6',
    title: 'Quantum Paradox',
    year: 2026,
    overview: 'Scientists accidentally create a rift in spacetime, forcing them to navigate alternate realities to fix it.',
    runtime: 135,
    genres: ['Sci-Fi', 'Mystery'],
    poster: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 7.8,
    contentRating: '16+',
    director: 'Christopher Nolan III',
    cast: ['Lead Actor', 'Supporting Actress']
  }
];
